# Generated by Django 6.0.4 on 2026-06-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cart_cartitem_order_orderitem_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/reviews/'),
        ),
    ]
