# Generated by Django 6.0.4 on 2026-06-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_is_featured_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Return_Requested', 'Return Requested'), ('Returned', 'Returned')], default='Pending', max_length=20),
        ),
    ]
