# Generated by Django 6.0.4 on 2026-06-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='MiniMart', max_length=100)),
                ('contact_email', models.EmailField(default='admin@minimart.com', max_length=254)),
                ('support_phone', models.CharField(default='+1-234-567-890', max_length=20)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
