# Generated by Django 6.0.4 on 2026-06-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_two_fa_enabled_userprofile_two_fa_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twofactorauth',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='two_fa_enabled',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='two_fa_method',
        ),
        migrations.DeleteModel(
            name='OTPToken',
        ),
        migrations.DeleteModel(
            name='TwoFactorAuth',
        ),
    ]
