# Generated by Django 6.0.4 on 2026-06-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_twofactorauth_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('UPI', 'UPI'), ('Wallet', 'Wallet'), ('GPay', 'GPay')], max_length=20),
        ),
    ]
