# Generated by Django 6.0.4 on 2026-06-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_paymentmethod_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('UPI', 'UPI'), ('Wallet', 'Wallet'), ('GPay', 'GPay'), ('COD', 'Cash on Delivery')], max_length=20),
        ),
    ]
